server:
  port: 8083
spring:
  application:
    name: Leave
eureka:
  instance:
    prefer-ip-address:true
  client:
    fetch-registry:true
    register-with-eureka:true
  server-url:
    defaultZone: http://localhost:8761/eureka

